language: bash
sudo: required
env:
    - TRAVIS=true
before_install:
    - sudo add-apt-repository ppa:duggan/bats --yes
    - sudo apt-get update -q
    - sudo apt-get install -q bats
script:
    - bats tests/apkbuild-lint.bats
notifications:
    email: true
